name: Deploy Azure Container App with OIDC

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write          # Needed for OIDC token request
  contents: read           # For checkout

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login via OIDC
        uses: azure/login@v2
        with:
          auth-type: oidc
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

      - name: Deploy to Azure Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          resourceGroup: ${{ secrets.AZURE_RESOURCE_GROUP }}
          containerAppName: ${{ secrets.AZURE_CONTAINER_APP_NAME }}
          imageToDeploy: ghcr.io/${{ github.repository }}:latest
